### ISSUE TITLE
How to add additional configurations to CI?

### ISSUE THREAD

**Issue by bennoleslie** [seL4/seL4#522] opened 2021-08-30 08:57 UTC
Assuming that  #520 is merged I would like to be able to ensure it is at least build tested as part of CI.

Ideally it would be built with the following configurations (which have all been tested and are known to work):

* `-DPLATFORM=tqma8xqp1gb -DRELEASE=OFF -DMCS=OFF -DSMP=OFF`
* `-DPLATFORM=tqma8xqp1gb -DRELEASE=OFF -DMCS=OFF -DSMP=ON`
* `-DPLATFORM=tqma8xqp1gb -DRELEASE=OFF -DMCS=ON -DSMP=OFF`
* `-DPLATFORM=tqma8xqp1gb -DRELEASE=OFF -DMCS=ON -DSMP=ON`
* `-DPLATFORM=tqma8xqp1gb -DRELEASE=ON -DMCS=OFF -DSMP=OFF`
* `-DPLATFORM=tqma8xqp1gb -DRELEASE=ON -DMCS=OFF -DSMP=ON`
* `-DPLATFORM=tqma8xqp1gb -DRELEASE=ON -DMCS=ON -DSMP=OFF`
* `-DPLATFORM=tqma8xqp1gb -DRELEASE=ON -DMCS=ON -DSMP=ON`

Is the CI configuration stored in a repo somewhere?
This adds some amount of load to the build system, is this acceptable?

**Comment by lsf37** [comment] 2021-08-30 22:42
Yes, the tested platforms are listed in the [seL4/ci-actions](https://github.com/seL4/ci-actions) repo in [platforms.yml](https://github.com/seL4/ci-actions/blob/master/seL4-platforms/platforms.yml).

To add the configurations above, we should add a new platform `tqma8xqp1gb` roughly like this:
```yaml
TQMA8XQP1GB:
    arch: arm
    modes: [64]
    smp: [64]
    hyp: [64]
    platform: tqma8xqp1gb
    march: armv8a
```

This will add it to compile tests automatically. I'll put up a PR for it.

**Comment by lsf37** [comment] 2021-08-31 00:36
I added `aarch_hyp` as in the example, but I guess that is not ready yet and waiting for something like #378, so will remove that bit again.

**Comment by lsf37** [comment] 2021-08-31 04:08
Ok this now appears to be working as intended. We can add the hyp config again when that part is merged.

**Closed by lsf37** 2021-08-31 04:08 UTC
Labels: question
