### ISSUE TITLE
rockpro64: sel4test IPC0001 freezes with 6-core SMP on pinebook pro

### ISSUE THREAD

**Issue by canarysnort01** [seL4/seL4#184] opened 2020-02-24 08:56 UTC
When building sel4test with these options and running on a pinebook pro (rockpro64 platform):

```
mkdir sel4test
cd sel4test
repo init -u https://github.com/seL4/sel4test-manifest.git -b master
repo sync
mkdir build
cd build
../init-build.sh -DPLATFORM=rockpro64 -DSIMULATION=FALSE -DSMP=ON -DNUM_NODES=6 -DLibUtilsDefaultZfLogLevel=0
ninja
cd images
../../tools/seL4/cmake-tool/helpers/make-uimage /usr/bin/aarch64-linux-gnu-objcopy ../elfloader/elfloader arm64 sel4test-driver-image-arm-rockpro64-uboot
```

sel4test freezes at this point while running the IPC0001 test:

```
Running test IPC0001 (Test SMP seL4_Send + seL4_Recv)
vka_alloc_reply@object.h:195 Allocating reply on non RT kernel
vka_alloc_reply@object.h:195 Allocating reply on non RT kernel
test_ipc_pair@ipc.c:300 98 <- 100
test_ipc_pair@ipc.c:300 98 -> 100
test_ipc_pair@ipc.c:300 99 <- 100
test_ipc_pair@ipc.c:300 99 -> 100
test_ipc_pair@ipc.c:300 100 <- 100
test_ipc_pair@ipc.c:300 100 -> 100
test_ipc_pair@ipc.c:300 101 <- 100
test_ipc_pair@ipc.c:300 101 -> 100
test_ipc_pair@ipc.c:300 102 <- 100
test_ipc_pair@ipc.c:300 102 -> 100
test_ipc_pair@ipc.c:300 98 <- 100
test_ipc_pair@ipc.c:300 98 -> 100
test_ipc_pair@ipc.c:300 99 <- 100
test_ipc_pair@ipc.c:300 99 -> 100
test_ipc_pair@ipc.c:300 100 <- 100
test_ipc_pair@ipc.c:300 100 -> 100
test_ipc_pair@ipc.c:300 101 <- 100
test_ipc_pair@ipc.c:300 101 -> 100
test_ipc_pair@ipc.c:300 102 <- 100
test_ipc_pair@ipc.c:300 102 -> 100
test_ipc_pair@ipc.c:300 98 <- 100
test_ipc_pair@ipc.c:300 98 -> 100
test_ipc_pair@ipc.c:300 99 <- 100
test_ipc_pair@ipc.c:300 99 -> 100
test_ipc_pair@ipc.c:300 100 <- 100
test_ipc_pair@ipc.c:300 100 -> 100
test_ipc_pair@ipc.c:300 101 <- 100
test_ipc_pair@ipc.c:300 101 -> 100
test_ipc_pair@ipc.c:300 102 <- 100
test_ipc_pair@ipc.c:300 102 -> 100
test_ipc_pair@ipc.c:300 98 <- 100
test_ipc_pair@ipc.c:300 98 -> 100
test_ipc_pair@ipc.c:300 99 <- 100
test_ipc_pair@ipc.c:300 99 -> 100
test_ipc_pair@ipc.c:300 100 <- 100
test_ipc_pair@ipc.c:300 100 -> 100
test_ipc_pair@ipc.c:300 101 <- 100
test_ipc_pair@ipc.c:300 101 -> 100
test_ipc_pair@ipc.c:300 102 <- 100
test_ipc_pair@ipc.c:300 102 -> 100
test_ipc_pair@ipc.c:300 98 <- 100
```

Note that sel4test completes successfully when only configured to use 4 cores.

These are the cores that were set up by elfloader when configured with 6 cores:

```
Boot cpu id = 0x0, index=0
Core 1 is up with logic id 1
Core 2 is up with logic id 2
Core 3 is up with logic id 3
Core 256 is up with logic id 4
Core 257 is up with logic id 5
```

The rockpro64 use the RK3399 SoC which has 4 Cortex-A53 cores and 2 Cortex-A72 cores.

Full serial output: [serial.txt](https://github.com/seL4/seL4/files/4243642/serial.txt)

**Comment by kent-mcleod** [comment] 2020-02-24 17:08
Thanks for reporting this.  We currently only test it with the first 4 A53 cores.  I'm also not aware of any platforms that we test the kernel on that use Cortex-A72 yet. There also any deliberate support for simultaneously running cores of different micro-architectures

**Comment by yyshen** [comment] 2020-02-28 01:20
Hello, thanks for reporting the issue. Based on the log, my guess is that code for sending IPIs needs to deal with the case that the target cores are in a different cluster. We do not have the board you mentioned, but I will take a look.

**Comment by canarysnort01** [comment] 2020-04-10 17:37
Thanks for looking at this. On further thought and discussion, do you think it is appropriate to model the big.LITTLE architecture CPUs as SMP, or would it be better to treat them as separate CPUs and run a multikernel on them?

**Comment by yyshen** [comment] 2020-06-19 15:02
> Thanks for looking at this. On further thought and discussion, do you think it is appropriate to model the big.LITTLE architecture CPUs as SMP, or would it be better to treat them as separate CPUs and run a multikernel on them?

I am sorry for getting back so late. It looks like the A53 cluster and A72 cluster have dedicated unified L2 caches. However, there is a CCI500 to ensure cache coherence between the clusters; so I think it is straight-forward to use one kernel to manage the clusters. On mobile phones, big.LITTLE requires an optimal scheduling for saving battery and achieving good performance, so moving processes between the clusters is probably needed.  

Of course, nothing prevents you from running a multikernel on the clusters. It depends on what applications you want to run on the clusters.

BTW, are you able to test an image on the pinebook? I do not have an RK3399-based board.

**Comment by canarysnort01** [comment] 2020-06-20 05:49
@yyshen Yes, I can test an image.

**Comment by yyshen** [comment] 2020-06-20 13:51
> @yyshen Yes, I can test an image.

Hi @canarysnort01 Please try the following image on pinebook pro and let me know the results.

[sel4test-driver-image-arm-rockpro64.zip](https://github.com/seL4/seL4/files/4807972/sel4test-driver-image-arm-rockpro64.zip)

**Comment by canarysnort01** [comment] 2020-06-21 14:53
Sorry, I forgot to mention that I'm not sure how to boot the image the build system creates on the pinebook pro.

Could you run the following from your ```build/images``` directory:

```
../../tools/seL4/cmake-tool/helpers/make-uimage /usr/bin/aarch64-linux-gnu-objcopy ../elfloader/elfloader arm64 sel4test-driver-image-arm-rockpro64-uboot
```

And provide me the ```sel4test-driver-image-arm-rockpro64-uboot``` file?

**Comment by yyshen** [comment] 2020-06-22 00:37
> Sorry, I forgot to mention that I'm not sure how to boot the image the build system creates on the pinebook pro.
> 
> Could you run the following from your `build/images` directory:
> 
> ```
> ../../tools/seL4/cmake-tool/helpers/make-uimage /usr/bin/aarch64-linux-gnu-objcopy ../elfloader/elfloader arm64 sel4test-driver-image-arm-rockpro64-uboot
> ```
> 
> And provide me the `sel4test-driver-image-arm-rockpro64-uboot` file?

I hope the following file is what you needed. 

[sel4test-driver-image-arm-rockpro64-uboot.gz](https://github.com/seL4/seL4/files/4810624/sel4test-driver-image-arm-rockpro64-uboot.gz)

**Comment by canarysnort01** [comment] 2020-06-22 13:39
Thanks @yyshen, that is what I needed.

Looks good!

```
Test suite passed. 133 tests passed. 36 tests disabled.
All is well in the universe
```

[Full serial output](https://github.com/seL4/seL4/files/4813507/serial2.txt)

**Comment by yyshen** [comment] 2020-06-22 13:44
> Thanks @yyshen, that is what I needed.
> 
> Looks good!
> 
> ```
> Test suite passed. 133 tests passed. 36 tests disabled.
> All is well in the universe
> ```
> 
> [Full serial output](https://github.com/seL4/seL4/files/4813507/serial2.txt)

@canarysnort01 Thanks for testing. It looks the fix worked. I will create a PR for the IPI issue, but I need to make sure I did not break other platforms.

**Comment by yyshen** [comment] 2020-06-28 05:07
Link to PR #213

**Comment by yyshen** [comment] 2020-08-07 05:59
@canarysnort01 #213 is merged. Please let me know if the commits resolve the issue.

**Comment by canarysnort01** [comment] 2020-08-09 02:32
Hello @yyshen 

I believe your kernel changes have resolved the issue.

However, there appears to be a new issue somewhere in either sel4test or one of the seL4 user libraries preventing any rockpro64 smp builds from passing the tests. If this isn't something you're aware of I can create a new github issue for you.

## What worked

First, let me tell you what worked. I checked out sel4test for 11.0.0, and then updated the kernel and seL4 tools to master, built with SMP with 6 cores, and ran sel4test on my pinebook pro. This was successful.

The complete build steps for this scenario:

```sh
mkdir sel4test
cd sel4test
repo init -u https://github.com/seL4/sel4test-manifest.git -b refs/tags/11.0.0
repo sync
cd kernel
git checkout master
cd ../tools/seL4
git checkout master
cd ../..
mkdir build
cd build
../init-build.sh -DPLATFORM=rockpro64 -DSIMULATION=false -DSMP=on -DNUM_NODES=6 -DLibUtilsDefaultZfLogLevel=0
ninja
cd images
../../tools/seL4/cmake-tool/helpers/make-uimage /usr/bin/aarch64-linux-gnu-objcopy ../elfloader/elfloader arm64 sel4test-driver-image-arm-rockpro64-uboot
```

When run on the pinebook pro, this resulted in success:

```
Starting test 132: Test all tests ran
Test suite passed. 132 tests passed. 35 tests disabled.
All is well in the universe
```

## What failed

When I checked out sel4test against master, then updated the kernel to master to include your recent changes, sel4test froze while running BIND0001.

I verified that this was NOT caused by your kernel changes by redoing the test I did previously in this thread with an older kernel with SMP for only 4 cores. This used to work successfully but freezes now at the same point in BIND0001.

It appears that some relatively change in either sel4test or one of the seL4 user libraries doesn't work on rockpro64 with SMP enabled.

The complete build steps for this scenario:

```sh
mkdir sel4test
cd sel4test
repo init -u https://github.com/seL4/sel4test-manifest.git -b master
repo sync
cd kernel
git checkout master
cd ..
mkdir build
cd build
../init-build.sh -DPLATFORM=rockpro64 -DSIMULATION=false -DSMP=on -DNUM_NODES=4 -DLibUtilsDefaultZfLogLevel=0
ninja
cd images
../../tools/seL4/cmake-tool/helpers/make-uimage /usr/bin/aarch64-linux-gnu-objcopy ../elfloader/elfloader arm64 sel4test-driver-image-arm-rockpro64-uboot
```

When run on the pinebook pro, this resulted in a freeze while running this test:

```
Starting test 18: BIND0001
sel4utils_spawn_process_v@process.c:383 Starting process at 0x4001c8, stack 0x10011df0
```

**Comment by canarysnort01** [comment] 2020-08-09 03:04
Here's the full serial output for the test that failed: [serial3.txt](https://github.com/seL4/seL4/files/5046704/serial3.txt)

**Comment by yyshen** [comment] 2020-08-10 04:09
> Here's the full serial output for the test that failed: [serial3.txt](https://github.com/seL4/seL4/files/5046704/serial3.txt)

@canarysnort01 Thanks for your investigation. I suggest we create another issue to track the hang. @branden-data61 Can we repeat the failure case?

**Comment by yyshen** [comment] 2020-08-27 12:48
> > Here's the full serial output for the test that failed: [serial3.txt](https://github.com/seL4/seL4/files/5046704/serial3.txt)
> 
> @canarysnort01 Thanks for your investigation. I suggest we create another issue to track the hang. @branden-data61 Can we repeat the failure case?

@branden-data61 Ping again. Could someone repeat the failure case internally?

**Comment by walle-whale** [comment] 2020-08-27 13:47
I'll try it tomorrow :+1:

**Comment by yyshen** [comment] 2020-08-27 13:49
> I'll try it tomorrow 👍

cool, thanks!

**Comment by abrandnewusername** [comment] 2020-08-28 07:26
Have reproduced exactly the same failure in internal sel4test repo.

**Comment by walle-whale** [comment] 2020-08-28 07:32
> Have reproduced exactly the same failure in internal sel4test repo.

Thanks :)

**Comment by canarysnort01** [comment] 2020-08-28 09:27
Thanks, I'm not sure which repository I should file a new issue against?

**Comment by yyshen** [comment] 2020-08-28 11:00
> Thanks, I'm not sure which repository I should file a new issue against?

this repo https://github.com/seL4/sel4test maybe?

**Closed** 2020-09-09 03:51 UTC

**Comment by xurtis** [comment] 2020-09-10 02:50
sel4/util_libs#39 seems to resolve part of the underlying issue somehow but now the 6-core SMP configuration seems to hang at `IPC1001` instead of `IPC0001` now (the inter-AS variant).

**Comment by xurtis** [comment] 2020-09-10 03:03
Actually, it looks good now, just that the IPC tests between address spaces across clusters is very slow.
