### ISSUE TITLE
Building kernel.elf for ArmCortexA8 Platform Causes compile_assert

### ISSUE THREAD

**Issue by sbosnick** [seL4/seL4#116] opened 2019-01-28 00:18 UTC
Building kernel.elf for either the omap3 or am335x platforms with the configuration option `HardwareDebugAPI` on will cause a compile_assert() for the `tcb_size_not_excessive` assertion. This assertion was introduced by commit bce62b4.

The smallest way to reproduce this that I have found is to run the following from a build subdirectory of the seL4 directory:

```sh
$ cmake .. -G Ninja -DCMAKE_TOOLCHAIN_FILE=../gcc.cmake -DKernelARMPlatform=am335x -DAARCH32=1 -DKernelVerificationBuild=OFF -DHardwareDebugAPI=ON -DKernelArch=arm -DKernelArmSel4Arch=aarch32
$ ninja kernel.elf
```

The same assertion is triggered for `-DKernelARMPlatform=omap3`.

**Comment by axel-h** [comment] 2021-09-19 23:49
Has anybody else seen this issue happening? I never had any problems building `am335x`

**Comment by lsf37** [comment] 2021-09-19 23:53
It's possible that specific combinations might make the TCB size too large, which would trigger something like this assertion. Let me try to reproduce.

**Comment by axel-h** [comment] 2021-09-20 00:03
`am335x` now sets `KernelHardwareDebugAPIUnsupported`, so `HardwareDebugAPI` cannot be enabled nowadays there. When I build there are just some warnings that definitions from `libsel4bench/arch_include/arm/cpu/cortex-a8/sel4bench/cpu/events.h`conflict with these from `libsel4bench/arch_include/arm/armv/armv7-a/sel4bench/armv/events.h`.

**Comment by lsf37** [comment] 2021-09-20 00:05
Yes, same result here. I think `KernelHardwareDebugAPIUnsupported` is the key that led to the assertion failure. The HW debug API increases the TCB size.

**Comment by lsf37** [comment] 2021-09-20 00:07
Closing this issue since it has been resolved by now with the explicit `KernelHardwareDebugAPIUnsupported` for `am335x`.

**Closed by lsf37** 2021-09-20 00:07 UTC
