### ISSUE TITLE
QEMU RISC-V Logging "Invalid register read" and "Invalid enable write" for the Sifive PLIC

### ISSUE THREAD

**Issue by midnightveil** [seL4/seL4#1350] opened 2024-11-08 03:09 UTC
I've been experiencing some strange behaviour in QEMU and on real hardware (Star64) with PCIe level-triggered interrupts that I don't see on AArch64 (QEMU or iMX8). I'm not entirely sure whether these are related to this issue, or if this is completely benign, but there's something funny going on. Specifically, in QEMU RISC-V I see a /single/ PCIe interrupt for a level triggered interrupt even when I don't write to the registers to clear it -- so according to PCIe there is still an asserted interrupt -- but I only ever get one from seL4.

---

Running the [microkit hello example](https://github.com/seL4/microkit/tree/main/example/qemu_virt_riscv64/hello), which just prints hello — the client doesn't matter as these errors are printed before the kernel even starts the root task — in QEMU prints out a long series of on boot. `qemu-system-riscv64 -machine virt -serial mon:stdio -kernel build/loader.img -m size=2G -nographic -d guest_errors`. Interrupts still /somewhat/ work (the timer interrupts are definitely happening), but I don't know what or why these happen. (Or if it's a QEMU issue).

```
Init local IRQ
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
...
Initializing PLIC...
sifive_plic_read: Invalid register read 0x1010
sifive_plic_write: Invalid register write 0x180
sifive_plic_write: Invalid register write 0x184
...
sifive_plic_read: Invalid register read 0x2090
sifive_plic_write: Invalid enable write 0x2090
Booting all finished, dropped to user space
```

<details>
<summary>Full boot logs</summary>

```
$ qemu-system-riscv64 -machine virt -serial mon:stdio -kernel build/loader.img -m size=2G -nographic -d guest_errors

OpenSBI v1.3.1
   ____                    _____ ____ _____
  / __ \                  / ____|  _ \_   _|
 | |  | |_ __   ___ _ __ | (___ | |_) || |
 | |  | | '_ \ / _ \ '_ \ \___ \|  _ < | |
 | |__| | |_) |  __/ | | |____) | |_) || |_
  \____/| .__/ \___|_| |_|_____/|___/_____|
        | |
        |_|

Platform Name             : riscv-virtio,qemu
Platform Features         : medeleg
Platform HART Count       : 1
Platform IPI Device       : aclint-mswi
Platform Timer Device     : aclint-mtimer @ 10000000Hz
Platform Console Device   : uart8250
Platform HSM Device       : ---
Platform PMU Device       : ---
Platform Reboot Device    : sifive_test
Platform Shutdown Device  : sifive_test
Platform Suspend Device   : ---
Platform CPPC Device      : ---
Firmware Base             : 0x80000000
Firmware Size             : 194 KB
Firmware RW Offset        : 0x20000
Firmware RW Size          : 66 KB
Firmware Heap Offset      : 0x28000
Firmware Heap Size        : 34 KB (total), 2 KB (reserved), 9 KB (used), 22 KB (free)
Firmware Scratch Size     : 4096 B (total), 760 B (used), 3336 B (free)
Runtime SBI Version       : 1.0

Domain0 Name              : root
Domain0 Boot HART         : 0
Domain0 HARTs             : 0*
Domain0 Region00          : 0x0000000002000000-0x000000000200ffff M: (I,R,W) S/U: ()
Domain0 Region01          : 0x0000000080000000-0x000000008001ffff M: (R,X) S/U: ()
Domain0 Region02          : 0x0000000080020000-0x000000008003ffff M: (R,W) S/U: ()
Domain0 Region03          : 0x0000000000000000-0xffffffffffffffff M: (R,W,X) S/U: (R,W,X)
Domain0 Next Address      : 0x0000000080200000
Domain0 Next Arg1         : 0x00000000bfe00000
Domain0 Next Mode         : S-mode
Domain0 SysReset          : yes
Domain0 SysSuspend        : yes

Boot HART ID              : 0
Boot HART Domain          : root
Boot HART Priv Version    : v1.12
Boot HART Base ISA        : rv64imafdch
Boot HART ISA Extensions  : time,sstc
Boot HART PMP Count       : 16
Boot HART PMP Granularity : 4
Boot HART PMP Address Bits: 54
Boot HART MHPM Count      : 16
Boot HART MIDELEG         : 0x0000000000001666
Boot HART MEDELEG         : 0x0000000000f0b509
LDR|INFO: altloader for seL4 starting
LDR|INFO: Flags:                0x0000000000000000
LDR|INFO: Kernel:      entry:   0xffffffff84000000
LDR|INFO: Root server: physmem: 0x0000000084030000 -- 0x0000000084036000
LDR|INFO:              virtmem: 0x000000008a000000 -- 0x000000008a006000
LDR|INFO:              entry  : 0x000000008a000000
LDR|INFO: region: 0x00000000   addr: 0x0000000084000000   size: 0x000000000002d000   offset: 0x0000000000000000   type: 0x0000000000000001
LDR|INFO: region: 0x00000001   addr: 0x0000000084030000   size: 0x0000000000005e68   offset: 0x000000000002d000   type: 0x0000000000000001
LDR|INFO: region: 0x00000002   addr: 0x000000008402d000   size: 0x00000000000008e8   offset: 0x0000000000032e68   type: 0x0000000000000001
LDR|INFO: region: 0x00000003   addr: 0x000000008402e000   size: 0x0000000000000290   offset: 0x0000000000033750   type: 0x0000000000000001
LDR|INFO: region: 0x00000004   addr: 0x000000008402f000   size: 0x0000000000000030   offset: 0x00000000000339e0   type: 0x0000000000000001
LDR|INFO: copying region 0x00000000
LDR|INFO: copying region 0x00000001
LDR|INFO: copying region 0x00000002
LDR|INFO: copying region 0x00000003
LDR|INFO: copying region 0x00000004
LDR|INFO: enabling MMU
LDR|INFO: jumping to kernel
Init local IRQ
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x2090
sifive_plic_write: Invalid enable write 0x2090
Bootstrapping kernel
Initializing PLIC...
sifive_plic_read: Invalid register read 0x1010
sifive_plic_write: Invalid register write 0x180
sifive_plic_write: Invalid register write 0x184
sifive_plic_write: Invalid register write 0x188
sifive_plic_write: Invalid register write 0x18c
sifive_plic_write: Invalid register write 0x190
sifive_plic_write: Invalid register write 0x194
sifive_plic_write: Invalid register write 0x198
sifive_plic_write: Invalid register write 0x19c
sifive_plic_write: Invalid register write 0x1a0
sifive_plic_write: Invalid register write 0x1a4
sifive_plic_write: Invalid register write 0x1a8
sifive_plic_write: Invalid register write 0x1ac
sifive_plic_write: Invalid register write 0x1b0
sifive_plic_write: Invalid register write 0x1b4
sifive_plic_write: Invalid register write 0x1b8
sifive_plic_write: Invalid register write 0x1bc
sifive_plic_write: Invalid register write 0x1c0
sifive_plic_write: Invalid register write 0x1c4
sifive_plic_write: Invalid register write 0x1c8
sifive_plic_write: Invalid register write 0x1cc
sifive_plic_write: Invalid register write 0x1d0
sifive_plic_write: Invalid register write 0x1d4
sifive_plic_write: Invalid register write 0x1d8
sifive_plic_write: Invalid register write 0x1dc
sifive_plic_write: Invalid register write 0x1e0
sifive_plic_write: Invalid register write 0x1e4
sifive_plic_write: Invalid register write 0x1e8
sifive_plic_write: Invalid register write 0x1ec
sifive_plic_write: Invalid register write 0x1f0
sifive_plic_write: Invalid register write 0x1f4
sifive_plic_write: Invalid register write 0x1f8
sifive_plic_write: Invalid register write 0x1fc
sifive_plic_write: Invalid register write 0x200
sifive_plic_write: Invalid register write 0x204
available phys memory regions: 1
  [80200000..100000000]
reserved virt address space regions: 3
  [ffffffc084000000..ffffffc08402d000]
  [ffffffc08402d000..ffffffc084030000]
  [ffffffc084030000..ffffffc084036000]
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x208c
sifive_plic_write: Invalid enable write 0x208c
sifive_plic_read: Invalid register read 0x2090
sifive_plic_write: Invalid enable write 0x2090
Booting all finished, dropped to user space
MON|INFO: Microkit Bootstrap
MON|INFO: bootinfo untyped list matches expected list
MON|INFO: Number of bootstrap invocations: 0x00000009
MON|INFO: Number of system invocations:    0x00000023
MON|INFO: completed bootstrap invocations
MON|INFO: completed system invocations
hello, world
QEMU: Terminated
```

</details>

--- 

On a (semi)related note, the `setTrigger` has `HAVE_SET_TRIGGER=1` set even though it does nothing. This is odd.

https://github.com/seL4/seL4/blob/65825d4df8924c3dea07941dc3eac63e7fc32618/include/drivers/irq/riscv_plic0.h#L193-L199

**Comment by Indanz** [comment] 2024-11-08 09:12
There may also be a mismatch between the Microkit SDK's/seL4's DTS file and the hardware/QEMU. According to the seL4 DTS file, PLIC is at 0xc000000.

**Comment by Indanz** [comment] 2024-11-08 10:19
src/plat/star64/config.cmake has MAX_IRQ 136, while only 96 seem to work for you.

**Comment by Indanz** [comment] 2024-11-08 10:24
> NB: I'm not quite sure why there's both `PLIC_NUM_INTERRUPTS` and `PLIC_MAX_IRQ`.

Because the first platform IRQ may not start at 1.

> ```diff
> diff --git a/include/drivers/irq/riscv_plic0.h b/include/drivers/irq/riscv_plic0.h
> index 0f5ab066d..bd5fa0b8c 100644
> --- a/include/drivers/irq/riscv_plic0.h
> +++ b/include/drivers/irq/riscv_plic0.h
> @@ -182,7 +182,7 @@ static inline void plic_init_controller(void)
>      }
> 
>      /* Set the priorities of all interrupts to 1 */
> -    for (int i = 1; i <= PLIC_MAX_IRQ + 1; i++) {
> +    for (int i = 1; i <= PLIC_MAX_IRQ; i++) {
>          writel(2, PLIC_PPTR_BASE + PLIC_PRIO + PLIC_PRIO_PER_ID * i);
>      }

In current code that's already fixed, what seL4 version are you using?

**Comment by Indanz** [comment] 2024-11-08 11:03
> This does not appear to be fixed? I was looking at the microkit branch.

Oops, indeed it isn't. I was looking at the loop above that.

> (... Is this not covered by verification?)

No, this is hardware specific bootup code, which isn't covered by the proofs.

There doesn't seem to be a way to discover the  number of IRQs at runtime, so we can't check it either.

**Comment by Indanz** [comment] 2024-11-08 11:19
There is already DTS parsing for some defines, see e.g. tools/hardware/irq.py, but I have no idea how it's used exactly.

**Comment by Indanz** [comment] 2024-11-08 11:24
Could you create a pull request with your changes, as well an update for tools/dts/star64.dts to change ndev to 0x5f?

We have a Star64 platform in CI, but it's currently not part of the tested machines.

**Comment by Indanz** [comment] 2024-11-08 11:30
Closing this issue as we found the cause and have a solution.

There already is an open issue that says we should use `ndev` directly instead of the separate define: #1031

**Closed by Indanz** 2024-11-08 11:30 UTC
