### ISSUE TITLE
Page fault on x86 kernel initialization with 2.1.0

### ISSUE THREAD

**Issue by chelmuth** [seL4/seL4#20] opened 2016-03-01 14:08 UTC
We have experimental support for seL4 as platform for [Genode](http://github.com/genodelabs/genode) and updated to 2.1.0 recently. Since then we've got strange page faults in *src/arch/x86/kernel/apic.c*.
```
========== KERNEL EXCEPTION ==========
Vector:  0xe
ErrCode: 0x0
IP:      0x100335
SP:      0xe0100de4
FLAGS:   0x96
CR0:     0x8000003b
CR2:     0x100335 (page-fault address)
CR3:     0x13a000 (page-directory physical address)
CR4:     0x290

Stack Dump:
*0xe0100de4 == 0xe0103097
...
```
From my investigation, this is caused by the call to `pit_init()` which is marked `PHYS_CODE`, but the calling function `apic_measure_freq()` is marked `BOOT_CODE` since 64aed5370af89e1e1ba751941582125adfca971c. Do we miss some detail when building seL4 for Genode?

**Comment by AdrianDanis** [comment] 2016-03-01 23:53
Looks like a latent bug on our end hidden by compiler optimizations. We typically don't build the kernel with anything less than `gcc -O2` and this seems to inline all the involved functions, resulting in no error. I can reproduce by compiling with `-Os` however.

Will push a fix for this, in the mean time you can either

* Increase the kernel optimization level
* Change `PHYS_CODE` to `BOOT_CODE` in `pit_init` and calls to `out8_phys` and `in8_phys` to just `out8` and `in8`

**Comment by chelmuth** [comment] 2016-03-02 07:30
Thanks, both workarounds work like a charm. The patch for *pit.c* I used can be found [here](https://gist.github.com/chelmuth/abfd91142fcd1e6ae208#file-sel4_pit_boot_code-patch).

**Closed** 2016-04-28 00:00 UTC
