### ISSUE TITLE
manual: Missing documentation for RISC-V seL4_IRQControl_GetTrigger

### ISSUE THREAD

**Issue by canarysnort01** [seL4/seL4#530] opened 2021-08-31 20:50 UTC
This is defined in the IDL but doesn't show up in the manual. I think it is because the interface name and method name are identical to one that exists on arm.

https://github.com/seL4/seL4/blob/12.1.0/libsel4/arch_include/riscv/interfaces/sel4arch.xml#L169

**Comment by canarysnort01** [comment] 2021-10-19 22:17
I've done some further analysis on this.

I can see that two definitions of `seL4_IRQControl_GetTrigger` are written into `manual/stage/object_invocations.h` by `manual/tools/gen_invocations.py`, one for ARM and another for RISC-V.

When doxygen processes this file, it appears to ignore the duplicate RISC-V definition, as `manual/doxygen-output/xml/group__riscv__seL4__IRQControl.xml` does not contain the definition.

**Comment by kent-mcleod** [comment] 2021-10-19 22:31
It makes sense to me that the issue is caused by Doxygen not allowing multiple functions with the same name within a single invocation. When I've run into this problem elsewhere the fix has been to have separate doxygen output xml folders and then selectively import functions into the document.

**Comment by lsf37** [comment] 2021-10-20 02:46
LaTeX is not the only thing generated, though, there is at least also markdown output, which goes onto the docs site, eg. <https://docs.sel4.systems/projects/sel4/api-doc.html#sel4_tcb>.

It may be sufficient to produce markdown directly, and convert that to LaTeX.

**Comment by lsf37** [comment] 2021-10-20 02:48
We could branch off just LaTeX and do a separate thing there, but that would make the output diverge and still leave the same issue for other formats. I'm not saying we need to stick with doxygen, but if we drop it, we should drop it for all of the paths.

**Comment by pingerino** [comment] 2021-10-20 03:02
I am somewhat responsible for the evolution of this tool chain of docs, so here's my 2c:

- The assumption was that some people would like to view the documentation as doxygen.
- It also allows us to generate docs for things not already in XML but comments in the C code. 

Ultimately my goal was to express the entire libsel4 api in a machine readable format and present consistent docs and code in whatever format was convenient for the consumer (latex vs in the code vs the doc site vs doxygen) that would always be up to date. 

The doxygen step was just a half way point that let us get the comments out of the code and out of the xml using an existing tool, but the intention was always to remove this step.

**Comment by lsf37** [comment] 2021-10-21 00:43
Generating libsel4 + possibly other language bindings is definitely on the cards. We're trying to line up some funding for that, and we should probably get the set of people together who are interested in the topic (specifically also for Rust bindings).

It doesn't look like funding for this will come through this year, but it wouldn't hurt hashing out what exactly we want and how we would go about it.

**Comment by canarysnort01** [comment] 2021-10-21 01:05
> Generating libsel4 + possibly other language bindings is definitely on the cards. We're trying to line up some funding for that, and we should probably get the set of people together who are interested in the topic (specifically also for Rust bindings).

Awesome!

This is something I am very interested in.

I have been thinking about this and prototyping some code to experiment with as part of the Robigalia project.

I would be willing to contribute time/code to get this implemented.

**Comment by lsf37** [comment] 2021-10-21 01:14
Cool! Things are somewhat busy at the moment, but we could try to set up a video call in a few weeks to talk about more details. I believe @kent-mcleod was interested in this as well.

@nspin would the Icecap project also be interested in generated language bindings (such as Rust)?

**Comment by nspin** [comment] 2021-11-03 22:08
(Late to this thread. Posting what I mentioned in yesterday's call for reference.)

`LibSel4FunctionAttributes=public` + automatic generation of FFI-level bindings has been serving us well, but the ability to generate bindings from the same source as that from which the C bindings are generated would certainly be a more robust foundation for user-level Rust code! We would also expect to contribute to this effort.

**Comment by Ivan-Velickovic** [comment] 2023-10-26 01:10
Turns out the `EXCLUDE` in the Makefile is not necessary anymore. It seems that Doxygen will separate out the MCS and non-MCS syscalls (`syscalls_master.h` and `syscalls_mcs.h`), even for syscalls that have the same function definition. Perhaps newer versions of Doxygen do this which is why the hack/workaround was initially needed?

Regarding this specific issue, the plan is to make the existing separate Doxygen groups into separate `.h` files rather than having everything in one `object_invocations.h`. It seems that Doxygen, despite functions having the same definitions, will respect duplicates as long as they are in separate groups *and* separate files. Currently things are only in separate Doxygen groups.

Myself and @lsf37 tested this out for the two definitions of `seL4_IRQControl_GetTrigger` and it seems to work.

**Comment by Ivan-Velickovic** [comment] 2023-10-26 01:12
The same approach should be able to be used to solve https://github.com/seL4/seL4/issues/558.

**Comment by lsf37** [comment] 2023-11-04 00:59
> Turns out the `EXCLUDE` in the Makefile is not necessary anymore. It seems that Doxygen will separate out the MCS and non-MCS syscalls (`syscalls_master.h` and `syscalls_mcs.h`), even for syscalls that have the same function definition. Perhaps newer versions of Doxygen do this which is why the hack/workaround was initially needed?

This might indeed depend on doxygen version, because when I re-ran this on my machine, I did get different output for some MCS syscalls with the EXCLUDE removed. They were basically description fields merged from the general and MCS syscalls. Inspecting the generated xml, it looks like for the MCS calls, it is still producing entries that have confused parameter lists and descriptions.

For the GetTrigger documentation on the other hand, it worked fine and generates correct xml.

**Comment by Ivan-Velickovic** [comment] 2023-11-05 13:13
> > Turns out the `EXCLUDE` in the Makefile is not necessary anymore. It seems that Doxygen will separate out the MCS and non-MCS syscalls (`syscalls_master.h` and `syscalls_mcs.h`), even for syscalls that have the same function definition. Perhaps newer versions of Doxygen do this which is why the hack/workaround was initially needed?
> 
> This might indeed depend on doxygen version, because when I re-ran this on my machine, I did get different output for some MCS syscalls with the EXCLUDE removed. They were basically description fields merged from the general and MCS syscalls. Inspecting the generated xml, it looks like for the MCS calls, it is still producing entries that have confused parameter lists and descriptions.
> 
> For the GetTrigger documentation on the other hand, it worked fine and generates correct xml.

Which MCS syscalls and which Doxygen version? This surprises me since the fix for IRQControl_GetTrigger is essentially what we already have for the MCS syscalls.

**Comment by lsf37** [comment] 2023-11-05 21:30
> Which MCS syscalls and which Doxygen version? This surprises me since the fix for IRQControl_GetTrigger is essentially what we already have for the MCS syscalls.

If you compare `sel4_mcs_send` vs `sel4_send`, the MCS version has the reference to section 2 twice -- one from the occurrence in GeneralSystemCalls and one from MCSSystemCalls (if you change the text in GeneralSystemCalls you'll see the change popping up in the MCS version). The most recent doxygen version I've tried is 1.9.7.

**Closed** 2023-11-07 05:12 UTC
Labels: docs
